### ISSUE TITLE
Figure out tagging data json structure

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/psi-dashboard#20]
For now I have this idea
```json
{
    "type":"water or skip or tag",
    "imageId":"5e669584b9a86b631c8cc511",
    "tags":{
        "impactType":"0",
        "devType":"0",
        "washoverType":"0",
        "damageType":"0"
    }
}
```

**Comment by ShahNafisRafique** [comment]
I think I have come up with a good json structure for a tag

```json
{
    "userId":"SomeUserId",
    "timeFinished":"1/1/40000",
    "timeAssigned":"1/1/30000",
    "sessionStartTime":"1/1/35000",
    "type":"water || skip || data",
    "data": {
        "impactType":"0",
        "devType":"0",
        "washoverType":"0",
        "terrianTypes":["0","2","3"],
        "damageType":"0"
    }
}
```

If "type" is water or skip, there will be no data property.

**Comment by ebgoldstein** [comment]
looks good to me!.. impact type is one of 5 types right? —  'nothing or swash or collision or overwash or inundation'

**Comment by ShahNafisRafique** [comment]
The difference is `"0"` is just that one category. So `impactType` is either no impact("0") or has impact("1") it can never be both. With `["0","1",...]` its a combination so mix and match the different categories or if its `[]` that means none of the categories apply.

**Comment by ebgoldstein** [comment]
ok, so:
`impactType` should be in brackets:  [0,1,2,3,4] (for 'nothing, swash, collision, overwash, inundation')
'terrainType' should have more categories... [0,1,2,3] (for 'sandy coastline, marsh, inland, river')

**Comment by ShahNafisRafique** [comment]
Yes. Actually now that I think about it, it would be best to have `terrianType` be 0,1,2,3,4] (for 'none, sandy coastline, marsh, inland, river') just to avoid empty entries. I will change `impactType` to be a checkbox and not a radio.

**Comment by ShahNafisRafique** [comment]
Quick question @ebgoldstein , what are the impact type values? It was a radio button before where the options where `impact` or `no impact`. What should the checkbox be this time? and does there need to be at least 1 selected or can it be like terrain where none can be selected?

**Comment by ebgoldstein** [comment]
types are: 
None, Swash, Collision, Overwash, Inundation
atleast 1 should be selected

**Comment by ShahNafisRafique** [comment]
Okay so I added in the correct names for impact and terrian checkboxes. This is the initial state of all the radios/checkboxes

```js
const initalTagState = {
    devType: -1, // radio
    washoverType: -1, // radio
    impactType: { // checkbox
      swash:0,
      collision:0,
      overwash:0,
      inundation:0
    },
    damageType: -1, // radio
    terrianType: { // checkbox
      sandyCoastline:0, 
      marsh:0, 
      inland:0, 
      river:0
    },
    waterOrOther: 0,
};
```

The radio buttons are set to `-1` which means nothing is selected, and in order to move on the value has to be 0 or more.

The checkboxes values are either 0 (not selected) or 1 (selceted). So for example if impact type is

```js
impactType: { // checkbox
      swash:0,
      collision:0,
      overwash:0,
      inundation:0
},
```
None of the checkboxes where selected, which means none. This way I dont have to add the 5th box called 'none'. I had the issue last semester where a user could select `none` and other tags and would resolve to `none` which didnt make sense from a user point of view. So if they want to tag none they just dont select anything and if they can check something they can. @ebgoldstein

**Comment by ShahNafisRafique** [comment]
![preview21](https://user-images.githubusercontent.com/38015120/79820708-e32e9e80-835a-11ea-90f7-ebc5b517a40d.PNG)
Heres a preview,ignore the section crossed out in red,its for debugging

**Comment by ebgoldstein** [comment]
this looks good @ShahNafisRafique !

**Comment by ShahNafisRafique** [comment]
Basic tagging with normal tags is successful
