### ISSUE TITLE
What to do if no new images in an archive.

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/psi-dashboard#21]
So for testing I have 4 images for a single archive. What should happen if a user has tagged all four images? I know this wont happen but might as well handle this edge case. Should I send a message saying  "No new image to tag for this archive"? @ebgoldstein

**Comment by ebgoldstein** [comment]
yes, message saying something like "no new images to tag in this archive [print archive name] — please contact an admin to get permission to tag a new archive".

**Comment by ShahNafisRafique** [comment]
Okay I can add that message. They dont need permission to tag a new archive since all archives under a storm are available.

**Comment by ShahNafisRafique** [comment]
![preview](https://user-images.githubusercontent.com/38015120/79819881-f50f4200-8358-11ea-97e9-adffab9aa5a6.PNG)
@ebgoldstein I added a message like this, just to make it look nice.
