### ISSUE TITLE
landing/welcome

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/psi-dashboard#28]
You have tagged 'X' images in 'XYZ' storms.. give a % complete for each storm.

**Comment by ebgoldstein** [comment]
allow them to continue on current storm.. or start on a new storm

**Comment by ShahNafisRafique** [comment]
@ebgoldstein How is this so far, I added a user message which is a field in the user model and the continue tagging button. They can start on a new storm by clicking the `Image Tag` button on the left

![homepage](https://user-images.githubusercontent.com/38015120/81465199-32b3fd80-9196-11ea-961c-bbf9b37d49a4.PNG)

**Comment by ebgoldstein** [comment]
I don't think i want a custom user message. Just say instructions —  like 'Click on the Image tag (on the left) to start tagging images.

and I'd remove USGS data link on the left (since we dont; ahve that data)

**Comment by ShahNafisRafique** [comment]
I can do that. Just an idea what  about links to the JOSS paper or the repos/organization?

**Comment by ebgoldstein** [comment]
eventually we need a link to some page that summarizes the whole effort... So maybe leave a comment or a line of code commented where a link can be inserted when i get my act together

**Comment by ebgoldstein** [comment]
but for now, lets not have a link
