### ISSUE TITLE
damage to infrastructure tag

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/psi-dashboard#4]

**Comment by ShahNafisRafique** [comment]
@ebgoldstein What would you like me to do for this issue? I am working on the ocean tag and was curious what to do for this.

**Comment by ebgoldstein** [comment]
maybe just a radio button that someone can press to indicate that the images shows damage to houses/buildings/roads

**Comment by ShahNafisRafique** [comment]
Okay should this be a new category or under impact? And is it just no damage vs damage?

**Comment by ebgoldstein** [comment]
I think this is experimental RN.... so a new category i think... and just damage vs no damage.

**Comment by ShahNafisRafique** [comment]
Added to tagging questions
