### ISSUE TITLE
Storm based or archive based permissions to tag

### ISSUE THREAD

**Issue by ShahNafisRafique** [UNCG-DAISY/psi-dashboard#7]
@ebgoldstein I have a question about how to give permissions to a tagger on what they can tag. Theres two ways that I see.

First way is each user object has a list of storms they can tag, and in that storm they can tag any image from any of the archives. On the dashboard I would then show them a list of storms and they select which storm to tag.

**Example** is, say Storm A has 5 archives, if someone has Storm A on their profile, they can tag any image from any of the 5 archives.

The second way is the user object has a list of all archives a user can tag,and they can only tag images from that archive. On the dashboard I would show them a list of archives they can tag.  I could try to group the archives by storm for display purpose.

**Example** is say Storm A has archives (A1,A2,A3) and Storm B has archives (B1,B2,B3). Lets say a user has A2,A3 and B1 on their profile, I could first ask the user what storm they want to tag and show Storm A and B (Since atleast one archive the user can tag is in one of those storms) and then show the archives they can tag based of that storm. 

The second way is a little bit more work, but very much possible.

**Comment by ebgoldstein** [comment]
First way is fine with me!

**Comment by ebgoldstein** [comment]
I think you solved this...
